services:
  processing-service:
    build: .
    ports:
      - "8083:8083"
    environment:
      AWS_ENDPOINT_OVERRIDE: http://video2frames-localstack:4566
      LOG_FORMAT: ${LOG_FORMAT:-}
    networks:
      - default
      - video2frames-net

networks:
  video2frames-net:
    external: true
