spring:
  application:
    name: video2frames-processing-service
  profiles:
    active: dev

server:
  port: ${SERVER_PORT:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    br.com.video2frames: ${LOG_LEVEL:INFO}
  structured:
    format:
      console: ${LOG_FORMAT:}

aws:
  region: ${AWS_REGION:us-east-1}
  endpoint-override: ${AWS_ENDPOINT_OVERRIDE:http://localhost:4566}
  access-key: ${AWS_ACCESS_KEY_ID:test}
  secret-key: ${AWS_SECRET_ACCESS_KEY:test}
  s3:
    bucket: ${S3_BUCKET:video2frames}
  sqs:
    video-uploaded-queue: ${SQS_VIDEO_UPLOADED_QUEUE:video-uploaded}
    video-processed-queue: ${SQS_VIDEO_PROCESSED_QUEUE:video-processed}
    video-failed-queue: ${SQS_VIDEO_FAILED_QUEUE:video-failed}
    video-processed-notif-queue: ${SQS_VIDEO_PROCESSED_NOTIF_QUEUE:video-processed-notif}
    video-failed-notif-queue: ${SQS_VIDEO_FAILED_NOTIF_QUEUE:video-failed-notif}
    poll-wait-time-seconds: 10

app:
  ffmpeg:
    binary-path: ${FFMPEG_PATH:ffmpeg}
  processing:
    concurrency: ${PROCESSING_CONCURRENCY:4}
